In [1]:
import pandas as pd

In [2]:
# 1. Create a DataFrame for the 201908-citibike-tripdata data. 
df = pd.read_csv('201908-citibike-tripdata.csv/201908-citibike-tripdata.csv')
df.sample(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
245582,621,2019-08-03 22:50:11.1210,2019-08-03 23:00:32.5980,435.0,W 21 St & 6 Ave,40.741740,-73.994156,128.0,MacDougal St & Prince St,40.727103,-74.002971,21118,Subscriber,1971,1
121964,1227,2019-08-02 13:37:47.1730,2019-08-02 13:58:14.2110,296.0,Division St & Bowery,40.714131,-73.997047,241.0,DeKalb Ave & S Portland Ave,40.689810,-73.974931,18386,Customer,1969,0
1634002,1755,2019-08-22 11:15:06.1470,2019-08-22 11:44:21.7970,426.0,West St & Chambers St,40.717548,-74.013221,426.0,West St & Chambers St,40.717548,-74.013221,25486,Subscriber,1992,2
2195858,900,2019-08-29 20:44:57.5300,2019-08-29 20:59:58.0720,410.0,Suffolk St & Stanton St,40.720664,-73.985180,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,33953,Subscriber,1989,2
199652,1780,2019-08-03 13:04:07.0100,2019-08-03 13:33:47.0330,3771.0,McKibbin St & Bogart St,40.706237,-73.933871,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,28109,Customer,1992,2
710742,1772,2019-08-10 11:17:53.5310,2019-08-10 11:47:25.5790,3641.0,Broadway & W 25 St,40.742869,-73.989186,508.0,W 46 St & 11 Ave,40.763414,-73.996674,17404,Customer,1969,0
2341187,153,2019-08-31 22:04:30.3290,2019-08-31 22:07:04.1520,3232.0,Bond St & Fulton St,40.689622,-73.983043,3440.0,Fulton St & Adams St,40.692418,-73.989495,31977,Subscriber,1989,1
590861,2037,2019-08-08 18:26:18.5250,2019-08-08 19:00:16.2850,3461.0,Murray St & Greenwich St,40.714852,-74.011223,3166.0,Riverside Dr & W 72 St,40.780578,-73.985624,29363,Subscriber,1961,1
1550442,496,2019-08-21 08:46:36.0710,2019-08-21 08:54:52.2540,466.0,W 25 St & 6 Ave,40.743954,-73.991449,116.0,W 17 St & 8 Ave,40.741776,-74.001497,15530,Subscriber,1989,1
1827188,700,2019-08-25 09:12:28.2260,2019-08-25 09:24:08.3340,481.0,S 3 St & Bedford Ave,40.712605,-73.962644,3107.0,Bedford Ave & Nassau Ave,40.723117,-73.952123,28137,Subscriber,1991,2

In [3]:
# 2. Check the datatypes of your columns. 
df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id           float64
start station name          object
start station latitude     float64
start station longitude    float64
end station id             float64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [4]:
# 3. Convert the 'tripduration' column to datetime datatype.
df['tripduration'] = pd.to_datetime(df['tripduration'], unit='s')
df.sample(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
1024914,1970-01-01 00:11:34,2019-08-14 09:52:21.3700,2019-08-14 10:03:55.5310,490.0,8 Ave & W 33 St,40.751551,-73.993934,509.0,9 Ave & W 22 St,40.745497,-74.001971,39979,Subscriber,1979,1
571143,1970-01-01 00:09:54,2019-08-08 15:39:31.6370,2019-08-08 15:49:26.1280,359.0,E 47 St & Park Ave,40.755103,-73.974987,507.0,E 25 St & 2 Ave,40.739126,-73.979738,39871,Subscriber,1995,1
281362,1970-01-01 00:04:30,2019-08-04 15:19:31.4550,2019-08-04 15:24:02.0730,312.0,Allen St & Stanton St,40.722055,-73.989111,251.0,Mott St & Prince St,40.723180,-73.994800,34029,Subscriber,1981,1
1406006,1970-01-01 01:00:48,2019-08-19 12:38:40.2250,2019-08-19 13:39:28.4800,3623.0,W 120 St & Claremont Ave,40.810949,-73.963400,3168.0,Central Park West & W 85 St,40.784727,-73.969617,30149,Customer,1991,1
2193493,1970-01-01 00:06:28,2019-08-29 20:10:15.6810,2019-08-29 20:16:44.2000,326.0,E 11 St & 1 Ave,40.729538,-73.984267,473.0,Rivington St & Chrystie St,40.721101,-73.991925,31018,Subscriber,1991,1
953123,1970-01-01 00:07:57,2019-08-13 11:15:19.4730,2019-08-13 11:23:17.1560,128.0,MacDougal St & Prince St,40.727103,-74.002971,238.0,Bank St & Washington St,40.736197,-74.008592,28390,Subscriber,1976,1
636371,1970-01-01 00:07:46,2019-08-09 11:33:44.1270,2019-08-09 11:41:30.7290,519.0,Pershing Square North,40.751873,-73.977706,491.0,E 24 St & Park Ave S,40.740964,-73.986022,31077,Subscriber,1983,1
1025856,1970-01-01 00:06:20,2019-08-14 10:07:47.9020,2019-08-14 10:14:08.6940,116.0,W 17 St & 8 Ave,40.741776,-74.001497,358.0,Christopher St & Greenwich St,40.732916,-74.007114,25052,Subscriber,1987,1
1365414,1970-01-01 00:13:38,2019-08-18 17:04:07.3710,2019-08-18 17:17:45.9540,432.0,E 7 St & Avenue A,40.726218,-73.983799,341.0,Stanton St & Mangin St,40.717821,-73.976289,38724,Subscriber,1993,1
1836006,1970-01-01 00:05:10,2019-08-25 11:37:06.6100,2019-08-25 11:42:17.1810,3641.0,Broadway & W 25 St,40.742869,-73.989186,3708.0,W 13 St & 5 Ave,40.735445,-73.994310,32808,Subscriber,1986,1

In [7]:
# 4. Check the datatypes of your columns. 
df.dtypes

tripduration               datetime64[ns]
starttime                          object
stoptime                           object
start station id                  float64
start station name                 object
start station latitude            float64
start station longitude           float64
end station id                    float64
end station name                   object
end station latitude              float64
end station longitude             float64
bikeid                              int64
usertype                           object
birth year                          int64
gender                              int64
dtype: object

In [9]:
# 5. Export the Dataframe as a new CSV file without the index.
df.to_csv('updated-trip-data.csv', index=False)